___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list = [5,10,15,20,25]
arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [4]:
arr_ones = np.ones((4,4), dtype=int)
arr_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [5]:
arr_ones * 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [6]:
arr_full = np.full((4,4), 7)
arr_full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [7]:
arr_even = np.arange(2,17,2)
arr_even

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [8]:
arr1 = np.arange(25).reshape(5,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [9]:
arr = np.linspace(0,24,25, dtype=int).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [10]:
arr = np.random.rand(5)
arr

array([0.88445662, 0.12252819, 0.60862575, 0.70629404, 0.42961434])

#### 11. Create random normal distributed 5x5 array

In [11]:
arr = np.random.randn(5,5)
arr

array([[-2.10998129, -0.65880483, -1.52765552,  1.01053553, -0.53524023],
       [ 1.09645885, -1.3130765 ,  0.47336532,  0.24770959, -0.67695916],
       [-0.73034931,  0.45267723,  0.66613869,  0.23194879,  0.5409058 ],
       [ 0.16860662, -0.2808989 ,  0.2574468 , -0.80727184, -0.04963125],
       [-1.51830266, -0.45331567, -0.6794149 , -0.77537255, -0.31419212]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [12]:
arr = np.random.randint(20,50, size=(3,4))
arr

array([[21, 21, 42, 22],
       [33, 22, 36, 27],
       [24, 39, 23, 44]])

#### 13. Reshape the array below with shape 6x8

In [13]:
ranarr = np.random.randint(0, 60, 48)
ranarr

array([41, 35, 46, 26, 17, 49, 13, 57, 11, 28,  6,  4, 52, 20, 16, 22, 20,
       49, 35, 22, 43, 36, 14, 43, 41, 47, 26, 13, 39, 16, 11, 50,  9,  1,
       28, 41, 13, 27,  8,  1,  4,  4, 51, 20, 56, 33,  0, 27])

In [14]:
ranarr.reshape(6,8)

array([[41, 35, 46, 26, 17, 49, 13, 57],
       [11, 28,  6,  4, 52, 20, 16, 22],
       [20, 49, 35, 22, 43, 36, 14, 43],
       [41, 47, 26, 13, 39, 16, 11, 50],
       [ 9,  1, 28, 41, 13, 27,  8,  1],
       [ 4,  4, 51, 20, 56, 33,  0, 27]])

In [15]:
ranarr.reshape(-1,8)

array([[41, 35, 46, 26, 17, 49, 13, 57],
       [11, 28,  6,  4, 52, 20, 16, 22],
       [20, 49, 35, 22, 43, 36, 14, 43],
       [41, 47, 26, 13, 39, 16, 11, 50],
       [ 9,  1, 28, 41, 13, 27,  8,  1],
       [ 4,  4, 51, 20, 56, 33,  0, 27]])

## Numpy Indexing and Selection


In [16]:
#Create array below


In [17]:
arr1 = np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [18]:
arr1[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [19]:
arr1[:, 0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [20]:
arr1[1, ::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [21]:
arr1[:, 2] = 77
arr1

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 1st row 0 column, 3th row 2nd column.

In [22]:
arr1[[1,3],[0,2]]

array([ 5, 77])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [23]:
arr1[1::2, ::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [24]:
a = arr1[arr1<10]
a

array([1, 2, 4, 5, 6, 8, 9])

In [25]:
b = arr1[arr1>12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [26]:
a+b

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [27]:
np.std(a+b)

29.700546274093877

#### 22. Get the sum of second column from array above

In [28]:
arr1

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [29]:
np.sum(arr1[:, 1])

32

#### 23. Get the median,mean and std of 3rd column from array above

In [30]:
np.median(arr1[:, 3])

10.0

In [31]:
arr1[:, 3]

array([ 4,  8, 12, 16])

In [32]:
np.mean(arr1[:, 3])

10.0

In [33]:
np.std(arr1[:, 3])

4.47213595499958

# Pandas Section

In [34]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [35]:
df = pd.read_csv("Data/Salaries.csv")

In [36]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [38]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year value are there**

In [39]:
df["Year"].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [40]:
len(df['Year'].unique())

4

**Print out max and avg Totalpay**

In [41]:
df["TotalPay"].describe()

count    148654.000000
mean      74768.321972
std       50517.005274
min        -618.130000
25%       36168.995000
50%       71426.610000
75%      105839.135000
max      567595.430000
Name: TotalPay, dtype: float64

In [42]:
df["TotalPay"].max()

567595.43

In [43]:
avg = df["TotalPay"].mean()
avg

74768.32197169267

**How many records are there which have TotalPay bigger than avg TotalPay**

In [44]:
len(df[df["TotalPay"] > avg])

69489

In [45]:
(df.TotalPay>avg).sum()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [46]:
df["TotalPayBenefits"][df["EmployeeName"] == "ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [47]:
df["EmployeeName"].loc[df["TotalPayBenefits"] == df["TotalPayBenefits"].min()]

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [52]:
df["EmployeeName"][df["TotalPay"].argmin()]

'Joe Lopez'

**What are the unique Jobs in dataset?**

In [48]:
df["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [49]:
df['JobTitle'].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [50]:
len(df[(df["TotalPayBenefits"] > df["TotalPayBenefits"].mean()) & (df["Year"] == 2012)])

20366

In [56]:
df["Id"][(df["TotalPayBenefits"] > df["TotalPayBenefits"].mean()) & (df["Year"] == 2012)].count()

20366

**How many people have the word Manager in their job title?**

In [61]:
aa = df.apply(lambda x: "manager" in x["JobTitle"].lower(), axis=1)
aa.sum()

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [62]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [65]:
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

    TotalPay  TotalPayBenefits  
0  567595.43         567595.43  
1  538909.28         538909.28  
2  335279.91         335279.91  
3  332343.61         332343.61  
4  326373.19         326373.19

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [68]:
sal_new = sal_new.loc[:, "EmployeeName":"TotalPayBenefits"]
sal_new.head()

EmployeeName                                        JobTitle  \
0     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

    TotalPay  TotalPayBenefits  
0  567595.43         567595.43  
1  538909.28         538909.28  
2  335279.91         335279.91  
3  332343.61         332343.61  
4  326373.19         326373.19

**Print out the names of the employees who earn more than min, but less than avg**

In [70]:
pay_min = sal_new["TotalPayBenefits"].min()
pay_min

-618.13

In [72]:
pay_ave = sal_new["TotalPayBenefits"].mean()
pay_ave

93692.55481056681

In [74]:
sal_new["EmployeeName"].loc[(sal_new["TotalPayBenefits"] > pay_min) & (sal_new["TotalPayBenefits"] < pay_ave)]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object